export type Blend = {
  slug: string; name: string; description: string; category: string; subcategory: string;
  tags: string[]; plugins: string[]; publisher: string; version: string; license: string; pulls: string;
};

export const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

// The real, complete 100-category software taxonomy this registry is organized
// around (docs/acrylbelnds_100ctgs/acrylbelnds_100ctgs.md in the acryl repo).
// A category with zero Blends is still a real, addressable node — not hidden —
// per the design doc's own "no Blends here yet" empty state.
const categoriesRaw: { name: string; subs: string[] }[] = [
  { name: "System", subs: ["Operating systems", "Kernels", "Device drivers", "Firmware", "Boot software", "System utilities"] },
  { name: "Application", subs: ["Productivity", "Personal information management", "Communication", "Collaboration"] },
  { name: "Business", subs: ["ERP", "CRM", "Finance", "Payments", "HR", "Project management", "Procurement", "Operations"] },
  { name: "Developer", subs: ["Code editors", "IDEs", "Version control", "Build tools", "Language tooling", "Dependency management", "Testing", "API development", "Developer collaboration"] },
  { name: "AI", subs: ["AI assistants", "AI agents", "Agent infrastructure", "Machine learning software", "Generative AI", "AI infrastructure", "AI safety"] },
  { name: "Data", subs: ["Databases", "Data engineering", "Data platforms", "Data governance"] },
  { name: "Analytics", subs: ["Business intelligence", "Data science", "Product analytics", "Web analytics", "Observability analytics"] },
  { name: "Cloud", subs: ["Cloud infrastructure", "Cloud management", "Container infrastructure", "Cloud platforms"] },
  { name: "DevOps", subs: ["CI/CD", "Infrastructure automation", "Observability", "Reliability"] },
  { name: "Networking", subs: ["Network infrastructure", "Network services", "Network management"] },
  { name: "Cybersecurity", subs: ["Endpoint security", "Network security", "Identity security", "Application security", "Cloud security", "Security operations", "Privacy"] },
  { name: "Internet", subs: ["Browsers", "Search", "Web servers", "Internet publishing"] },
  { name: "Media", subs: ["Graphics", "Video", "Audio", "Music", "Plugins"] },
  { name: "3D / CAD / Design", subs: ["CAD", "3D", "BIM", "CAM", "CAE"] },
  { name: "Scientific & Engineering", subs: ["Mathematics", "Statistics", "Science", "Engineering"] },
  { name: "Industrial", subs: ["Manufacturing", "Industrial control", "Digital twins"] },
  { name: "Robotics", subs: ["Robot operating systems", "Motion planning", "Navigation", "SLAM", "Computer vision"] },
  { name: "Embedded / IoT", subs: ["IoT platforms", "Smart devices"] },
  { name: "Automotive", subs: ["Infotainment", "Navigation", "ADAS", "Autonomous driving", "Vehicle operating systems"] },
  { name: "Aerospace / Aviation", subs: ["Flight control", "Avionics", "Navigation", "Air traffic control", "Mission control"] },
  { name: "Geographic", subs: ["GIS", "Navigation", "Remote sensing"] },
  { name: "Education", subs: ["Learning management systems", "Course platforms", "Virtual classrooms", "Assessment tools"] },
  { name: "Healthcare", subs: ["Clinical", "Patient software", "Medical devices"] },
  { name: "Finance & Fintech", subs: ["Banking", "Trading", "Fintech", "Crypto"] },
  { name: "Legal", subs: ["Legal research", "Case management", "Contract lifecycle management", "Compliance"] },
  { name: "Government / Public Sector", subs: ["Tax administration", "Identity systems", "E-government portals", "Public records"] },
  { name: "Military / Defense", subs: ["Command and control", "Intelligence systems", "Battlefield management", "Simulation"] },
  { name: "Retail", subs: ["Point-of-sale", "Inventory", "Store management", "Retail analytics"] },
  { name: "E-commerce", subs: ["Online stores", "Marketplaces", "Order management", "Headless commerce"] },
  { name: "Marketing", subs: ["MarTech", "Advertising", "SEO"] },
  { name: "Sales", subs: ["CRM", "Sales engagement", "Lead generation", "Sales intelligence"] },
  { name: "Customer Service", subs: ["Help desks", "Ticketing", "Live chat", "Contact centers"] },
  { name: "Logistics", subs: ["Transportation management", "Warehouse management", "Fleet management", "Route optimization"] },
  { name: "Travel", subs: ["Booking engines", "Hotel management", "Airline reservation systems", "Travel planning"] },
  { name: "Hospitality", subs: ["Hotel PMS", "Restaurant POS", "Reservation systems", "Guest management"] },
  { name: "Real Estate", subs: ["Property management", "Real-estate CRM", "Listing platforms", "Mortgage software"] },
  { name: "Architecture / Construction", subs: ["BIM", "CAD", "Construction project management", "Estimation"] },
  { name: "Agriculture", subs: ["Farm management", "Precision agriculture", "Crop monitoring", "Yield prediction"] },
  { name: "Energy", subs: ["Grid management", "Smart grid", "Energy trading", "EV charging"] },
  { name: "Telecom", subs: ["OSS/BSS", "Billing", "Network management", "5G core"] },
  { name: "Gaming", subs: ["Games", "Game development", "Gaming platforms"] },
  { name: "Entertainment", subs: ["Streaming platforms", "Music streaming", "Video streaming", "Media centers"] },
  { name: "Social", subs: ["Social networks", "Forums", "Communities", "Livestreaming"] },
  { name: "Creator", subs: ["Content creation", "Newsletter platforms", "Podcasting", "Creator monetization"] },
  { name: "Publishing", subs: ["Desktop publishing", "Typesetting", "E-book production", "Editorial workflow"] },
  { name: "Office Automation", subs: ["Document generation", "Mail merge", "RPA", "E-signatures"] },
  { name: "Low-code / No-code", subs: ["App builders", "Website builders", "Workflow builders", "AI app builders"] },
  { name: "Automation", subs: ["RPA", "Workflow automation", "Browser automation"] },
  { name: "Search & Retrieval", subs: ["Search engines", "Enterprise search", "Semantic search", "Vector search"] },
  { name: "Knowledge", subs: ["Wikis", "Knowledge bases", "Knowledge graphs", "Reference managers"] },
  { name: "Simulation", subs: ["Physics simulation", "Digital twins", "Flight simulators", "Business simulation"] },
  { name: "Virtualization", subs: ["Hypervisors", "Virtual machines", "Desktop virtualization", "Storage virtualization"] },
  { name: "Remote Computing", subs: ["Remote desktop", "SSH clients", "VDI", "Remote development"] },
  { name: "Storage", subs: ["File systems", "Object storage", "Backup", "Synchronization"] },
  { name: "Distributed Systems", subs: ["Cluster management", "Distributed coordination", "Distributed databases", "Message brokers"] },
  { name: "Messaging Infrastructure", subs: ["Message queues", "Event buses", "Pub/sub", "Webhooks"] },
  { name: "Middleware", subs: ["Application servers", "RPC frameworks", "API gateways", "Integration middleware"] },
  { name: "Runtime", subs: ["Language runtimes", "JavaScript runtimes", "WebAssembly runtimes", "Container runtimes"] },
  { name: "Libraries & Frameworks", subs: ["Libraries", "Frameworks"] },
  { name: "API / SDK", subs: ["SDKs", "API clients", "Platform SDKs", "AI SDKs"] },
  { name: "Integration", subs: ["iPaaS", "ETL", "API integration", "Connectors"] },
  { name: "Mobile", subs: ["Native apps", "Hybrid apps", "Progressive web apps", "Mobile games"] },
  { name: "Desktop", subs: ["Native desktop apps", "Electron apps", "Tauri apps", "Qt apps"] },
  { name: "Web", subs: ["Websites", "Web apps", "SaaS apps", "Browser extensions"] },
  { name: "Terminal", subs: ["Shells", "Terminal emulators", "CLI tools", "TUIs"] },
  { name: "Extended Reality", subs: ["Virtual reality", "Augmented reality", "Mixed reality", "XR engines"] },
  { name: "Human-Computer Interaction", subs: ["Accessibility", "Screen readers", "Gesture recognition", "Brain-computer interfaces"] },
  { name: "Localization", subs: ["Translation management", "Machine translation", "CAT tools", "Internationalization tools"] },
  { name: "Accessibility", subs: ["Screen readers", "Magnifiers", "Speech recognition", "Captioning"] },
  { name: "Backup / Recovery", subs: ["Backup", "Snapshotting", "Disaster recovery", "File recovery"] },
  { name: "Compliance / Governance", subs: ["GRC", "Audit", "Risk management", "Regulatory compliance"] },
  { name: "Blockchain", subs: ["Blockchain nodes", "Smart contract platforms", "Wallets", "DeFi protocols"] },
  { name: "Decentralized", subs: ["Peer-to-peer systems", "Federated systems", "Distributed identity", "Web3 applications"] },
  { name: "Peer-to-Peer", subs: ["File sharing", "Communication", "Distributed computing", "P2P networking"] },
  { name: "Content Management", subs: ["CMS", "Headless CMS", "DAM", "ECM"] },
  { name: "File", subs: ["File managers", "File synchronization", "File conversion", "Compression"] },
  { name: "Digital Asset Management", subs: ["Images", "Video", "Brand assets", "Rights management"] },
  { name: "Identity", subs: ["Authentication", "Authorization", "SSO", "Directory services"] },
  { name: "Authentication", subs: ["Password authentication", "MFA", "Passwordless", "Biometrics"] },
  { name: "Cryptographic", subs: ["Encryption", "Key management", "PKI", "Digital signatures"] },
  { name: "Operating / Management Consoles", subs: ["Admin dashboards", "Control panels", "Management interfaces", "Operations consoles"] },
  { name: "Monitoring", subs: ["Infrastructure monitoring", "Application monitoring", "Security monitoring", "Uptime monitoring"] },
  { name: "Optimization", subs: ["Scheduling", "Routing", "Resource allocation", "Constraint solving"] },
  { name: "Scheduling", subs: ["Workforce scheduling", "Appointment scheduling", "Job scheduling", "Cloud workload scheduling"] },
  { name: "Workflow", subs: ["Human workflow", "Machine workflow", "Developer workflow", "Durable workflows"] },
  { name: "Document", subs: ["Editing", "Conversion", "PDF", "Document intelligence"] },
  { name: "Research", subs: ["Literature search", "Citation management", "Research notebooks", "Lab management"] },
  { name: "Information Management", subs: ["PIM", "ECM", "DAM", "Knowledge management"] },
  { name: "Personal", subs: ["Personal finance", "Fitness", "Journaling", "Life planning"] },
  { name: "Home", subs: ["Home automation", "Smart-home control", "Home security", "NAS management"] },
  { name: "Utilities", subs: ["Calculators", "Converters", "Clipboard managers", "Launchers"] },
  { name: "Emulation", subs: ["Console emulators", "CPU emulators", "OS emulators", "Compatibility layers"] },
  { name: "Compatibility", subs: ["Wine-like compatibility layers", "Translation layers", "Binary translation", "Legacy runtime compatibility"] },
  { name: "Licensing / Distribution", subs: ["App stores", "Package repositories", "License servers", "Update systems"] },
  { name: "Software Marketplaces", subs: ["App stores", "Plugin stores", "Extension marketplaces", "Agent marketplaces"] },
  { name: "Plugin / Extension Ecosystems", subs: ["Browser extensions", "IDE extensions", "AI skills", "MCP servers"] },
  { name: "Software Factories", subs: ["Code generation systems", "AI software factories", "Specification-driven development", "Multi-agent development systems"] },
  { name: "Self-modifying / Adaptive", subs: ["Self-updating applications", "Plugin-generating systems", "Generative UI", "Self-healing software"] },
  { name: "Autonomous", subs: ["Autonomous agents", "Autonomous vehicles", "Trading bots", "Self-healing systems"] },
  { name: "Meta-software", subs: ["Compilers", "AI coding agents", "Software factories", "DSLs"] },
];

export const categories = categoriesRaw.map((c) => ({ slug: slugify(c.name), name: c.name, subs: c.subs, count: 0 }));

// Illustrative preview Blends — real category/taxonomy alignment, real plugin
// package names drawn from acryldev/acryl where they exist (cordis-plugin-market,
// dsh-client-ui-brand-acryl, acryl-control, acryl-harness-runtime), fictional
// names elsewhere clearly scoped as preview data, not a claim of a populated registry.
export const blends: Blend[] = [
  { slug: "acryl", name: "ACRYL", description: "The flagship, maxed-out Blend. One complete expression of the model: agent control plane, terminal/web/desktop surfaces, editor, market and brand slots composed into a single working product.", category: "Developer", subcategory: "Agentic development environments", tags: ["flagship", "agents", "multi-surface"], plugins: ["cordis", "acryl-control", "acryl-harness-runtime", "cordis-plugin-market", "dsh-client-ui-brand-acryl"], publisher: "acryldev", version: "0.1.44", license: "MIT", pulls: "—" },
  { slug: "blank-canvas", name: "Blank Canvas", description: "The smallest viable Blend. Start empty, then grow only what the work needs.", category: "Developer", subcategory: "Code editors", tags: ["starter", "minimal", "hot-reload"], plugins: ["cordis"], publisher: "acrylblends", version: "0.1.0", license: "MIT", pulls: "—" },
  { slug: "agent-workbench", name: "Agent Workbench", description: "A focused environment for tool-using agents, evaluations, memory and human checkpoints.", category: "AI", subcategory: "Agent infrastructure", tags: ["agents", "evaluation", "memory"], plugins: ["cordis", "agent-runtime", "checkpoint-store", "tool-router"], publisher: "acrylblends", version: "0.1.0", license: "Apache-2.0", pulls: "—" },
  { slug: "local-first-studio", name: "Local-first Studio", description: "Desktop-ready composition with local storage, sync boundaries and a visual work surface.", category: "Application", subcategory: "Productivity", tags: ["desktop", "local-first", "sync"], plugins: ["cordis", "desktop-surface", "local-store", "sync-adapter"], publisher: "webboxes", version: "0.1.0", license: "MIT", pulls: "—" },
  { slug: "secure-ops", name: "Secure Ops", description: "Auditable operations console with identity, secrets and policy-aware tool execution.", category: "Cybersecurity", subcategory: "Identity security", tags: ["security", "audit", "operations"], plugins: ["cordis", "identity-gate", "secret-vault", "audit-log"], publisher: "webboxes", version: "0.1.0", license: "BUSL-1.1", pulls: "—" },
  { slug: "data-pipeline", name: "Data Pipeline", description: "Composable ingestion, transformation and validation for durable data workflows.", category: "Data", subcategory: "Data engineering", tags: ["data", "etl", "validation"], plugins: ["cordis", "source-connectors", "transform-engine", "schema-guard"], publisher: "community", version: "0.1.0", license: "MIT", pulls: "—" },
  { slug: "release-pilot", name: "Release Pilot", description: "A release engineering Blend for testing, packaging and coordinated deployments.", category: "DevOps", subcategory: "CI/CD", tags: ["release", "ci", "automation"], plugins: ["cordis", "test-runner", "release-graph", "deploy-adapter"], publisher: "community", version: "0.1.0", license: "MIT", pulls: "—" },
];

for (const c of categories) c.count = blends.filter((b) => b.category === c.name).length;

export const docGroups = [
  { slug: "getting-started", title: "Getting Started", items: ["What is ACRYL Blends", "Install", "Pull your first Blend", "Publish your first Cordis plugin"] },
  { slug: "core-concepts", title: "Core Concepts", items: ["Cordis plugins: the atom", "Blends: the composed instance", "The two registries", "The blank canvas", "ACRYL as a maxed-out Blend"] },
  { slug: "building-blocks", title: "Building Blocks", items: ["Generate a plugin from template", "Package identity convention", "Six-part mini-design", "Writing cordis.patch.yml", "Testing in isolation"] },
  { slug: "in-instance-authoring", title: "In-Instance Authoring", items: ["Hot-reload authoring", "Graduating a local plugin", "The acryl-package keyword", "Differentiation Engine"] },
  { slug: "building-and-publishing", title: "Build & Publish", items: ["The Blend YAML format", "Compose from plugins", "Categorize a Blend", "Publish to acrylblends", "Version and update"] },
  { slug: "nesting-and-composition", title: "Nesting & Composition", items: ["Grouping plugins into larger units"] },
  { slug: "private-and-enterprise", title: "Private & Enterprise", items: ["Self-hosted registries", "Private team catalogs", "Enterprise-only Blends"] },
  { slug: "resources", title: "Resources", items: ["CLI reference", "Examples", "FAQ", "Troubleshooting"] },
];
