import { Link, useParams } from "react-router-dom";
import { ArrowUpRight, Download, GitFork, History } from "lucide-react";
import { Breadcrumbs, SiteLayout, usePageMeta } from "../components/layouts";
import { CodeBlock, Status } from "../components/ui";
import { blends } from "../lib/content";
import NotFound from "./NotFound";

export default function BlendDetail() {
  const { slug } = useParams();
  const b = blends.find(x => x.slug === slug);
  usePageMeta(b?.name ?? "Blend", b?.description ?? "ACRYL Blend");
  if (!b) return <NotFound/>;
  const command = `acryl blend pull ${b.publisher}/${b.slug}@${b.version}`;
  return <SiteLayout><section className="border-b border-border bg-surface"><div className="mx-auto max-w-[1200px] px-5 py-14 md:px-8"><Breadcrumbs items={[{ label: "Blends", to: "/blends" }, { label: b.category, to: `/blends/${b.category.toLowerCase()}` }, { label: b.name }]}/><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2"><Status>{b.category}</Status><Status>{b.subcategory}</Status><Status tone="success">Stable</Status></div><h1 className="mt-5 text-4xl font-semibold md:text-6xl">{b.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">{b.description}</p></div><div className="grid min-w-60 grid-cols-2 border border-border bg-background"><Metric value={b.version} label="Version"/><Metric value={b.pulls} label="Pulls"/><Metric value={String(b.plugins.length)} label="Plugins"/><Metric value={b.license} label="License"/></div></div></div></section><div className="mx-auto grid max-w-[1200px] gap-10 px-5 py-12 md:px-8 lg:grid-cols-[1fr_300px]"><main><h2 className="text-2xl font-semibold">Pull this Blend</h2><div className="mt-4"><CodeBlock label="Terminal" code={command}/></div><h2 className="mt-12 text-2xl font-semibold">Composed plugins</h2><div className="mt-4 border-t border-border">{b.plugins.map((p, i) => <a key={p} href={`https://github.com/cordisplugins/${p}`} target="_blank" rel="noreferrer" className="flex items-center justify-between border-b border-border py-4 hover:text-accent-foreground"><div><span className="mr-4 font-mono text-[11px] text-muted-foreground">{String(i + 1).padStart(2, "0")}</span><strong className="font-mono text-sm">{p}</strong></div><ArrowUpRight size={15}/></a>)}</div><h2 className="mt-12 text-2xl font-semibold">Provenance</h2><div className="mt-4 border border-dashed border-border p-6"><div className="flex gap-3"><GitFork size={18}/><div><h3 className="font-semibold">Original composition</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">No parent Blend recorded. Differentiation history will appear here when the Differentiation Engine lands.</p></div></div></div></main><aside className="space-y-6"><Info label="Publisher" value={b.publisher}/><Info label="License" value={b.license}/><Info label="Updated" value="September 2026"/><div className="border-t border-border pt-6"><Link to="/docs/building-and-publishing/version-and-update" className="flex items-center gap-2 text-sm font-semibold"><History size={15}/> Version history</Link><button className="mt-4 flex items-center gap-2 text-sm font-semibold"><Download size={15}/> Export manifest</button></div></aside></div></SiteLayout>;
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="border-b border-r border-border p-4"><strong className="block text-lg">{value}</strong><span className="font-mono text-[10px] uppercase text-muted-foreground">{label}</span></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><span className="font-mono text-[10px] uppercase text-muted-foreground">{label}</span><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
