import { Link } from "react-router-dom";
import { ArrowRight, Boxes, Braces, Cable, Goal, Command, Layers3, MonitorSmartphone, Network, RotateCcw } from "lucide-react";
import { SiteLayout, usePageMeta } from "../components/layouts";
import { CodeBlock, Eyebrow, SectionTitle, TriangleMark } from "../components/ui";
import { categories } from "../lib/content";

const features = [
  [Braces, "Plugin scaffolding", "Generate the exact Cordis plugin shape your idea needs."],
  [RotateCcw, "In-instance authoring", "Build and hot-reload without leaving the running Blend."],
  [Layers3, "Blend YAML", "Describe a complete software instance as a readable recipe."],
  [Command, "One-command pull", "Pull a known starting point and bring it up in one motion."],
  [Boxes, "Category registry", "Navigate a durable taxonomy instead of a wall of packages."],
  [Network, "Private registries", "Keep proprietary compositions inside your own boundary."],
  [Goal, "Checkpoint & rollback", "Differentiate safely with traceable states and reversibility."],
  [MonitorSmartphone, "Many surfaces", "Compose TUI, web and desktop surfaces from the same core."],
  [Cable, "Harness compatible", "Cordis-native plugins remain usable beyond the ACRYL world."],
] as const;

const pluginCode = `import { Context } from 'cordis'\n\nexport const name = 'hello-world'\n\nexport function apply(ctx: Context) {\n  ctx.on('ready', () => {\n    ctx.logger.info('Blend is alive')\n  })\n}`;
const yamlCode = `name: agent-workbench\nversion: 0.1.0\nruntime: cordis\nplugins:\n  - agent-runtime\n  - tool-router\n  - checkpoint-store\n  - web-surface`;

export default function Home() {
  usePageMeta("AI development framework", "Compose stable software from Cordis plugins. Start with a Blend, grow it in place, and publish what works.");
  return <SiteLayout>
    <section className="relative overflow-hidden border-b border-border"><div className="geo-grid absolute inset-0 opacity-45"/><div className="relative mx-auto grid min-h-[calc(100vh-4rem)] max-w-[1440px] items-center gap-12 px-5 py-16 md:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div><Eyebrow>AI development framework · Based on Cordis</Eyebrow><h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[.98] tracking-normal sm:text-6xl lg:text-[5.6rem]">Start blank.<br/><span className="spectrum-text">Grow into anything.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Compose stable software from small Cordis plugins. Pull a proven starting point, shape it inside the running instance, then publish what works.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/blends" className="btn-primary">Browse Blends <ArrowRight size={16}/></Link><Link to="/docs" className="btn-secondary">Read the docs</Link></div><div className="mt-12 flex items-center gap-3 font-mono text-xs text-muted-foreground"><span className="h-px w-10 bg-border"/>OPEN SOURCE · COMPOSABLE · REVERSIBLE</div></div><LayerVisual/></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-24 md:px-8"><SectionTitle eyebrow="Framework primitives" title="Everything you need to grow a Blend" intro="Small, legible pieces from the first plugin to a complete software system."/><div className="mt-12 grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, body], i) => <div key={title as string} className="group border-b border-r border-border p-7 transition-colors hover:bg-surface"><div className="flex items-start justify-between"><Icon size={20} strokeWidth={1.6}/><span className="font-mono text-[10px] text-muted-foreground">0{i + 1}</span></div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div></section>
    <section className="border-y border-border bg-surface"><div className="mx-auto max-w-[1440px] px-5 py-24 md:px-8"><SectionTitle eyebrow="Readable by design" title="The atom and the recipe" intro="A plugin does one thing. A Blend names the things that become one working instance."/><div className="mt-12 grid gap-5 lg:grid-cols-2"><CodeBlock label="plugin.ts" code={pluginCode}/><CodeBlock label="blend.yml" code={yamlCode}/></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-24 md:px-8"><SectionTitle eyebrow="A short path" title="Pull. Grow. Publish."/><div className="mt-12 grid gap-px bg-border lg:grid-cols-3">{[["01", "Pull", "Choose a starting point and bring up a working Cordis instance."], ["02", "Grow", "Add and refine plugins inside the instance with hot reload."], ["03", "Publish", "Graduate a plugin to the market or the full composition to Blends."]].map(([n, t, b]) => <div key={t} className="bg-background p-8"><span className="font-mono text-xs text-accent-foreground">{n}</span><h3 className="mt-12 text-3xl font-semibold">{t}</h3><p className="mt-3 leading-7 text-muted-foreground">{b}</p></div>)}</div></section>
    <section className="border-y border-border bg-ink text-ink-foreground"><div className="mx-auto max-w-[1440px] px-5 py-24 md:px-8"><SectionTitle eyebrow="One of a hundred starting points" title="Find the right shape for the work" intro="Browse a stable taxonomy spanning systems, agents, infrastructure and everything between."/><div className="mt-12 grid gap-px bg-ink-border sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 8).map((c, i) => <Link key={c.slug} to={`/blends/${c.slug}`} className="group bg-ink p-6 hover:bg-ink-raised"><span className="font-mono text-[10px] text-ink-muted">{String(i + 1).padStart(2, "0")}</span><h3 className="mt-8 text-xl font-semibold">{c.name}</h3><p className="mt-2 text-sm text-ink-muted">{c.subs.slice(0, 2).join(" · ")}</p><ArrowRight className="mt-7 transition-transform group-hover:translate-x-1" size={16}/></Link>)}</div><Link to="/blends" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">Explore all 100 categories <ArrowRight size={15}/></Link></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 md:px-8"><div className="grid items-center gap-8 border-l-2 border-spectrum-start bg-surface px-7 py-10 md:grid-cols-[1fr_auto]"><div><Eyebrow>Open core, human support</Eyebrow><h2 className="mt-3 text-2xl font-semibold">Open source, built by Webboxes.</h2><p className="mt-2 text-muted-foreground">Consulting and private registries for teams building proprietary systems.</p></div><Link to="/ecosystem/business-model" className="btn-secondary">How the model works <ArrowRight size={15}/></Link></div></section>
  </SiteLayout>;
}
function LayerVisual() {
  return <div className="relative mx-auto w-full max-w-xl"><div className="absolute inset-0 m-auto h-[72%] w-[72%] rotate-45 border border-border"/><TriangleMark className="mx-auto h-64 w-64 md:h-80 md:w-80"/><div className="relative z-10 mt-10 grid grid-cols-3 gap-2">{[["01", "ATOM", "Cordis plugin"], ["02", "BLEND", "Composed instance"], ["03", "REGISTRY", "Starting points"]].map(([n, t, s]) => <div key={t} className="border-t border-border pt-3"><span className="font-mono text-[9px] text-muted-foreground">{n}</span><strong className="mt-1 block font-mono text-xs">{t}</strong><span className="mt-1 block text-[11px] text-muted-foreground">{s}</span></div>)}</div></div>;
}
