import { Link, useLocation } from "react-router-dom";
import { Menu, Search, X, ArrowUpRight, Layers3 } from "lucide-react";
import { useEffect, useState } from "react";
import { blends, categories, docGroups, slugify } from "../lib/content";

const nav = [{ to: "/", label: "Home" }, { to: "/blends", label: "Browse Blends" }, { to: "/docs", label: "Docs" }, { to: "/cordis", label: "Cordis Primer" }, { to: "/ecosystem", label: "Ecosystem" }, { to: "/blog", label: "Blog" }] as const;

function Mark({ className = "h-7 w-7" }: { className?: string }) {
  return <div className={`${className} grid shrink-0 place-items-center rounded-sm bg-primary text-primary-foreground`}><Layers3 size={16}/></div>;
}

export function Header() {
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false); const path = useLocation().pathname;
  useEffect(() => { const fn = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setSearch(true); } if (e.key === "Escape") setSearch(false); }; addEventListener("keydown", fn); return () => removeEventListener("keydown", fn); }, []);
  return <><header className="sticky top-0 z-40 border-b border-border/80 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-5 px-4 md:px-8"><Link to="/" className="flex shrink-0 items-center gap-2.5" aria-label="ACRYL Blends home"><Mark/><span className="text-sm font-bold tracking-[0.12em]">ACRYL <span className="text-muted-foreground">BLENDS</span></span></Link><nav className="hidden flex-1 items-center justify-center gap-1 xl:flex">{nav.map(item => <Link key={item.to} to={item.to} className={`nav-link ${path === item.to || (item.to !== "/" && path.startsWith(item.to)) ? "nav-link-active" : ""}`}>{item.label}</Link>)}</nav><div className="ml-auto flex items-center gap-2"><button onClick={() => setSearch(true)} className="search-trigger" aria-label="Search"><Search size={15}/><span className="hidden sm:inline">Search</span><kbd className="hidden lg:inline">⌘K</kbd></button><a href="https://github.com/acrylblends" target="_blank" rel="noreferrer" className="hidden text-sm font-medium text-muted-foreground hover:text-foreground md:inline-flex">GitHub <ArrowUpRight size={14}/></a><Link to="/blends" className="btn-primary hidden sm:inline-flex">Browse</Link><button onClick={() => setMenu(!menu)} className="icon-button xl:hidden" aria-label="Toggle navigation">{menu ? <X/> : <Menu/>}</button></div></div>{menu && <nav className="border-t border-border bg-background p-3 xl:hidden">{nav.map(item => <Link key={item.to} to={item.to} onClick={() => setMenu(false)} className="block rounded-sm px-3 py-3 text-sm font-medium hover:bg-muted">{item.label}</Link>)}</nav>}</header>{search && <SearchPanel onClose={() => setSearch(false)}/>}</>;
}
function SearchPanel({ onClose }: { onClose: () => void }) {
  const [q, setQ] = useState("");
  const entries = [...blends.map(b => ({ title: b.name, meta: "Blend", to: `/blends/b/${b.slug}` })), ...categories.map(c => ({ title: c.name, meta: "Category", to: `/blends/${c.slug}` })), ...docGroups.flatMap(g => g.items.map(i => ({ title: i, meta: g.title, to: `/docs/${g.slug}/${slugify(i)}` })))].filter(x => x.title.toLowerCase().includes(q.toLowerCase())).slice(0, 8);
  return <div className="fixed inset-0 z-50 bg-overlay p-4 pt-[10vh]" onMouseDown={onClose}><div className="mx-auto max-w-2xl overflow-hidden rounded-md border border-border bg-popover shadow-modal" onMouseDown={e => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4"><Search size={18} className="text-muted-foreground"/><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Search Blends, categories and docs…" className="h-14 flex-1 bg-transparent text-sm outline-none"/><button onClick={onClose} className="font-mono text-xs text-muted-foreground">ESC</button></div><div className="max-h-[60vh] overflow-auto p-2">{entries.map(e => <Link key={e.to} to={e.to} onClick={onClose} className="flex items-center justify-between rounded-sm px-3 py-3 hover:bg-muted"><span className="font-medium">{e.title}</span><span className="font-mono text-xs text-muted-foreground">{e.meta}</span></Link>)}{entries.length === 0 && <p className="p-6 text-center text-sm text-muted-foreground">No matching entries.</p>}</div></div></div>;
}
export function Footer() {
  return <footer className="border-t border-border bg-ink text-ink-foreground"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 md:grid-cols-[1.6fr_repeat(3,1fr)] md:px-8"><div><div className="flex items-center gap-3"><Mark className="h-9 w-9"/><span className="text-sm font-bold tracking-[0.14em]">ACRYL BLENDS</span></div><p className="mt-5 max-w-sm text-sm leading-6 text-ink-muted">A practical framework for composing stable software from Cordis plugins. Open source, built by Webboxes.</p></div><FooterCol title="Explore" links={[["Browse Blends", "/blends"], ["Documentation", "/docs"], ["Cordis Primer", "/cordis"], ["Blog", "/blog"]]}/><FooterCol title="Ecosystem" links={[["The three layers", "/ecosystem/three-layers"], ["Business model", "/ecosystem/business-model"], ["Roadmap", "/ecosystem/roadmap"], ["acryl.dev — the product", "https://acryl.dev"], ["cordisplugins.github.io — the plugin registry", "https://cordisplugins.github.io"]]}/><FooterCol title="Code" links={[["acrylblends.github.io", "https://github.com/acrylblends/acrylblends.github.io"], ["cordisplugins (org)", "https://github.com/cordisplugins"], ["acryldev/acryl", "https://github.com/acryldev/acryl"], ["DeepSeek Harness", "https://github.com/deepseek-ai"]]}/></div><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-2 border-t border-ink-border px-5 py-5 font-mono text-[11px] text-ink-muted md:flex-row md:px-8"><span>© 2026 ACRYL BLENDS</span><span>COMPOSABLE BY DESIGN · OPEN BY DEFAULT</span></div></footer>;
}
function FooterCol({ title, links }: { title: string; links: Array<[string, string]> }) {
  return <div><h3 className="font-mono text-xs font-semibold uppercase tracking-[0.14em]">{title}</h3><div className="mt-4 space-y-3">{links.map(([l, to]) => to.startsWith("http") ? <a key={l} href={to} className="block text-sm text-ink-muted hover:text-ink-foreground">{l}</a> : <Link key={l} to={to} className="block text-sm text-ink-muted hover:text-ink-foreground">{l}</Link>)}</div></div>;
}
